name: contracts tests

on:
  push:
    branches: [main]
    paths:
      - "contracts/**"
  pull_request:
    branches: [main]
    paths:
      - "contracts/**"
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd contracts
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd contracts
          forge test -vvv --fork-url https://arb-mainnet.g.alchemy.com/v2/$ALCHEMY_API_KEY --fork-block-number 104254482 --mp test/UniversalRouter.t.sol
          forge test -vvv --fork-url https://arb-mainnet.g.alchemy.com/v2/$ALCHEMY_API_KEY --fork-block-number 99515648 --mp test/LiquidityEventBackrun.t.sol
        id: test
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
