name: dexquote tests

on:
  push:
    branches: [ main ]
    paths:
      - "dexquote/src/**"
  pull_request:
    branches: [ main ]
    paths:
      - "dexquote/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./dexquote

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Run cargo check
        run: | 
          cargo check --all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    services:
      redis:
        image: ubuntu/redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 30073:6379
        env:
          REDIS_PASSWORD: testtest
      neo4j:
        image: neo4j
        options: >-
          --health-cmd "wget http://localhost:7474 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name neo4j-container
        ports:
          - 7474:7474
          - 7687:7687
        env:
          NEO4J_AUTH: "neo4j/testtest"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set a token address constraint
        run: |
          docker exec neo4j-container cypher-shell -u neo4j -p testtest "CREATE CONSTRAINT address_arb_constraint FOR (token:Arb) REQUIRE token.address IS UNIQUE"
      - name: Run cargo test
        run: |
          make test
        env: 
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      
      - name: Run server tests
        run: |
          make test
        working-directory: ./server
        env: 
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Run cargo fmt 
        run: |
          make fmt

      - name: Run cargo clippy
        run: |
          make clippy

  lines:
    name: Check source code lines
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install loc
      run: cargo install loc
    - name: Check lines
      run: loc