name: dexquote tests

on:
  push:
    branches: [ main ]
    paths:
      - "dexquote/src/**"
  pull_request:
    branches: [ main ]
    paths:
      - "dexquote/**"
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dexquote

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Run cargo check
        run: | 
          cargo check --all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Run cargo test
        run: |
          make test
        env: 
          JSON_RPC_URL: ${{ secrets.JSON_RPC_URL }}

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Run cargo fmt 
        run: |
          make fmt

      - name: Run cargo clippy
        run: |
          make clippy