name: UI test

on:
  push:
    branches: [ main ]
    paths:
      - 'ui/src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ui/src/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ui

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install 
      - name: Build
        run: yarn build
